name: CI

on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest
    container: docker://koyamanx/os1_dev:v1.0

    steps:
    - uses: actions/checkout@v3
    - name: build for CI
      run: ./run.sh build
