name: 'Doxygen deploy to GitHub pages'
author: 'Chihiro Koyama'
description: 'Deploy Doxygen genrated documentations to GitHub pages'

on:
  push:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: "Install Doxygen"
        run: sudo apt install -y doxygen graphviz
        shell: bash
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: "Generate Doxygen documentation"
        run: doxygen
        shell: bash
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "create .nojekyll"
        run: touch docs/html/.nojekyll
        shell: bash
      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs


